import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dark Screen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{
      background:'black'
    }}>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Azeret+Mono:wght@100;200;300;400;500;600;700;800;900&family=Gruppo&display=swap')
      </style>
      <body>
        {children}
      </body>
    </html>
  );
}
